# Generated by Django 5.1.4 on 2025-02-14 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_bm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('nome_de_guerra', models.CharField(max_length=20)),
                ('situacao', models.CharField(choices=[('', ' '), ('Efetivo', 'Efetivo'), ('Exonerado a Pedido', 'Exonerado a Pedido'), ('Exonerado Ex-Ofício', 'Exonerado Ex-Ofício'), ('Reserva a Pedido', 'Reserva a Pedido'), ('Transferido', 'Transferido')], default='Efetivo', max_length=30)),
                ('sgb', models.CharField(choices=[('', ' '), ('1ºSGB', '1ºSGB'), ('2ºSGB', '2ºSGB'), ('3ºSGB', '3ºSGB'), ('4ºSGB', '4ºSGB'), ('5ºSGB', '5ºSGB')], max_length=9)),
                ('posto_secao', models.CharField(choices=[('', ' '), ('703151101 - EB CERRADO', 'EB CERRADO'), ('703151102 - EB ZONA NORTE', 'EB ZONA NORTE'), ('703151201 - EB SANTA ROSÁLIA', 'EB SANTA ROSÁLIA'), ('703151202 - EB ÉDEM', 'EB ÉDEM'), ('703151301 - EB VOTORANTIM', 'EB VOTORANTIM'), ('703151302 - EB PIEDADE', 'EB PIEDADE'), ('703152101 - EB ITU', 'EB ITU'), ('703152102 - EB PORTO FELIZ', 'EB PORTO FELIZ'), ('703152201 - EB SALTO', 'EB SALTO'), ('703152301 - EB SÃO ROQUE', 'EB SÃO ROQUE'), ('703152302 - EB IBIÚNA', 'EB IBIÚNA'), ('703153101 - EB ITAPEVA', 'EB ITAPEVA'), ('703153102 - EB APIAÍ', 'EB APIAÍ'), ('703153103 - EB ITARARÉ', 'EB ITARARÉ'), ('703153104 - EB CAPÃO BONITO', 'EB CAPÃO BONITO'), ('703154101 - EB ITAPETININGA', 'EB ITAPETININGA'), ('703154102 - EB BOITUVA', 'EB BOITUVA'), ('703154103 - EB ANGATUBA', 'EB ANGATUBA'), ('703154201 - EB TATUÍ', 'EB TATUÍ'), ('703154202 - EB TIETÊ', 'EB TIETÊ'), ('703154203 - EB LARANJAL PAULISTA', 'EB LARANJAL PAULISTA'), ('703155101 - EB BOTUCATU', 'EB BOTUCATU'), ('703155102 - EB ITATINGA', 'EB ITATINGA'), ('703155201 - EB AVARÉ', 'EB AVARÉ'), ('703155202 - EB PIRAJU', 'EB PIRAJU'), ('703155203 - EB ITAÍ', 'EB ITAÍ')], max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=14)),
                ('cnh', models.CharField(max_length=14)),
                ('cat_cnh', models.CharField(choices=[('', ' '), ('A', 'A'), ('AB', 'AB'), ('AC', 'AC '), ('AD', 'AD'), ('AE', 'AE'), ('B', ' B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=4)),
                ('esb', models.CharField(choices=[('', ' '), ('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=4)),
                ('ovb', models.CharField(choices=[('', ' '), ('LEVE', 'LEVE'), ('PESADO', 'PESADO'), ('NÃO POSSUI', 'NÃO POSSUI')], max_length=10)),
                ('admissao', models.DateField()),
                ('nasc', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=14)),
                ('apresentacao_na_unidade', models.DateField()),
                ('saida_da_unidade', models.DateField(blank=True, null=True)),
                ('funcao', models.CharField(choices=[('', ' '), ('AUX (ADM)', 'AUX (ADM)'), ('AUXILIARES', 'AUXILIARES'), ('TELEGRAFISTA', 'TELEGRAFISTA'), ('MOTORISTA', 'MOTORISTA')], max_length=50)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('genero', models.CharField(choices=[('', ' '), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cadastros_bm', to=settings.AUTH_USER_MODEL)),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem_bm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/fotos_bm')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='bm.cadastro_bm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
