# Generated by Django 5.1.4 on 2025-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_bm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_bm',
            name='situacao',
            field=models.CharField(choices=[('', ' '), ('Efetivo', 'Efetivo'), ('Exonerado a Pedido', 'Exonerado a Pedido'), ('Exonerado Ex-Ofício', 'Exonerado Ex-Ofício'), ('Reserva a Pedido', 'Reserva a Pedido'), ('Transferido', 'Transferido')], default='Efetivo', max_length=30),
        ),
        migrations.AlterField(
            model_name='imagem_bm',
            name='image',
            field=models.ImageField(upload_to='img/fotos_bm'),
        ),
    ]
