# Generated by Django 5.1.4 on 2025-02-27 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('efetivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=6, unique=True)),
                ('dig', models.CharField(max_length=1)),
                ('posto_grad', models.CharField(choices=[('', ' '), ('Cel PM', 'Cel PM'), ('Ten Cel PM', 'Ten Cel PM'), ('Maj PM', 'Maj PM'), ('CAP PM', 'Cap PM'), ('1º Ten PM', '1º Ten PM'), ('1º Ten QAPM', '1º Ten QAOPM'), ('2º Ten PM', '2º Ten PM'), ('2º Ten QAPM', '2º Ten QAOPM'), ('Asp OF PM', 'Asp OF PM'), ('Subten PM', 'Subten PM'), ('1º Sgt PM', '1º Sgt PM'), ('2º Sgt PM', '2º Sgt PM'), ('3º Sgt PM', '3º Sgt PM'), ('Cb PM', 'Cb PM'), ('Sd PM', 'Sd PM'), ('Sd PM 2ºCL', 'Sd PM 2ºCL')], max_length=100)),
                ('image', models.ImageField(upload_to='img/fotos_perfil/usuario')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('tipo', models.CharField(choices=[('administrativo', 'Administrativo'), ('operacional', 'Operacional')], max_length=15)),
                ('cadastro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='efetivo.cadastro', verbose_name='cadastro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'ordering': ('user__first_name',),
            },
        ),
    ]
