# Generated by Django 5.1.4 on 2025-02-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhessituacao',
            name='situacao',
            field=models.CharField(choices=[('', ' '), ('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('LSV', 'LSV'), ('LTS', 'LTS'), ('LTS FAMILIA', 'LTS FAMILIA'), ('CONVAL', 'CONVAL'), ('ELEIÇÃO', 'ELEIÇAO'), ('LP', 'LP'), ('FERIAS', 'FÉRIAS')], default='Efetivo', max_length=30),
        ),
    ]
