# Generated by Django 5.1.4 on 2024-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0002_detalhessituacao_user_historicodetalhessituacao_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalhessituacao',
            old_name='user',
            new_name='usuario_alteracao',
        ),
        migrations.AlterField(
            model_name='imagem',
            name='image',
            field=models.ImageField(upload_to='backend/core/static/img/fotos_perfil'),
        ),
    ]
