# Generated by Django 5.1.4 on 2025-01-16 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0001_initial'),
        ('rpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_rpt',
            name='cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cadastro_rpt', to='efetivo.cadastro'),
        ),
    ]
