# Generated by Django 5.1.4 on 2025-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='municipio',
            field=models.CharField(choices=[('', ' '), ('Águas de Santa Bárbara', 'Águas de Santa Bárbara'), ('Apiaí', 'Apiaí'), ('Barra do Chapéu', 'Barra do Chapéu'), ('Alambari', 'Alambari'), ('Bom Sucesso de Itararé', 'Bom Sucesso de Itararé'), ('Alumínio', 'Alumínio'), ('Buri', 'Buri'), ('Capão Bonito', 'Capão Bonito'), ('Araçoiaba da Serra', 'Araçoiaba da Serra'), ('Angatuba', 'Angatuba'), ('Anhembi', 'Anhembi'), ('Araçariguama', 'Araçariguama'), ('Arandu', 'Arandu'), ('Areiópolis', 'Areiópolis'), ('Avaré', 'Avaré'), ('Campina do Monte Alegre', 'Campina do Monte Alegre'), ('Barão de Antonina', 'Barão de Antonina'), ('Boituva', 'Boituva'), ('Capela do Alto', 'Capela do Alto'), ('Botucatu', 'Botucatu'), ('Bofete', 'Bofete'), ('Cerqueira César', 'Cerqueira César'), ('Cerquilho', 'Cerquilho'), ('Cesário Lange', 'Cesário Lange'), ('Conchas', 'Conchas'), ('Coronel Macedo', 'Coronel Macedo'), ('Fartura', 'Fartura'), ('Guapiara', 'Guapiara'), ('Guareí', 'Guareí'), ('Iaras', 'Iaras'), ('Ibiúna', 'Ibiúna'), ('Iperó', 'Iperó'), ('Itaberá', 'Itaberá'), ('Itaí', 'Itaí'), ('Itaoca', 'Itaoca'), ('Itapetininga', 'Itapetininga'), ('Itapeva', 'Itapeva'), ('Itapirapuã Paulista', 'Itapirapuã Paulista'), ('Itaporanga', 'Itaporanga'), ('Itararé', 'Itararé'), ('Itatinga', 'Itatinga'), ('Itu', 'Itu'), ('Jumirim', 'Jumirim'), ('Laranjal Paulista', 'Laranjal Paulista'), ('Mairinque', 'Mairinque'), ('Manduri', 'Manduri'), ('Nova Campina', 'Nova Campina'), ('Paranapanema', 'Paranapanema'), ('Pardinho', 'Pardinho'), ('Pereiras', 'Pereiras'), ('Piedade', 'Piedade'), ('Pilar do Sul', 'Pilar do Sul'), ('Piraju', 'Piraju'), ('Porangaba', 'Porangaba'), ('Porto Feliz', 'Porto Feliz'), ('Pratânia', 'Pratânia'), ('Quadra', 'Quadra'), ('Ribeira', 'Ribeira'), ('Ribeirão Branco', 'Ribeirão Branco'), ('Ribeirão Grande', 'Ribeirão Grande'), ('Riversul', 'Riversul'), ('Salto', 'Salto'), ('Salto de Pirapora', 'Salto de Pirapora'), ('São Manuel', 'São Manuel'), ('São Miguel Arcanjo', 'São Miguel Arcanjo'), ('São Paulo', 'São Paulo'), ('São Roque', 'São Roque'), ('Sarapuí', 'Sarapuí'), ('Sarutaiá', 'Sarutaiá'), ('Sorocaba', 'Sorocaba'), ('Taguaí', 'Taguaí'), ('Tapiraí', 'Tapiraí'), ('Taquarituba', 'Taquarituba'), ('Taquarivaí', 'Taquarivaí'), ('Tatuí', 'Tatuí'), ('Tejupá', 'Tejupá'), ('Tietê', 'Tietê'), ('Torre de Pedra', 'Torre de Pedra'), ('Votorantim', 'Votorantim')], max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='contato',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contato',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='posto',
            name='cidade_posto',
            field=models.CharField(choices=[('', ' '), ('Sorocaba', 'Sorocaba'), ('Votorantim', 'Votorantim'), ('Piedade', 'Piedade'), ('Itu', 'Itu'), ('Porto Feliz', 'Porto Feliz'), ('Salto', 'Salto'), ('São Roque', 'São Roque'), ('Ibiúna', 'Ibiúna'), ('Itapeva', 'Itapeva'), ('Itararé', 'Itararé'), ('Apiaí', 'Apiaí'), ('Capão Bonito', 'Capão Bonito'), ('Itapetininga', 'Itapetininga'), ('Angatuba', 'Angatuba'), ('Boituva', 'Boituva'), ('Tatuí', 'Tatuí'), ('Tietê', 'Tietê'), ('Laranjal Paulista', 'Laranjal Paulista'), ('Botucatu', 'Botucatu'), ('Itaí', 'Itaí'), ('Avaré', 'Avaré'), ('Itatinga', 'Itatinga'), ('Piraju', 'Piraju')], max_length=50),
        ),
        migrations.AlterField(
            model_name='posto',
            name='posto_atendimento',
            field=models.CharField(choices=[('', ' '), ('EB AVARÉ', 'EB AVARÉ'), ('EB APIAÍ', 'EB APIAÍ'), ('EB ITAPETININGA', 'EB ITAPETININGA'), ('EB ITARARÉ', 'EB ITARARÉ'), ('EB SÃO ROQUE', 'EB SÃO ROQUE'), ('EB CAPÃO BONITO', 'EB CAPÃO BONITO'), ('EB CERRADO', 'EB CERRADO'), ('EB ANGATUBA', 'EB ANGATUBA'), ('EB BOTUCATU', 'EB BOTUCATU'), ('EB SALTO', 'EB SALTO'), ('EB ITAÍ', 'EB ITAÍ'), ('EB BOITUVA', 'EB BOITUVA'), ('EB TATUÍ', 'EB TATUÍ'), ('EB TIETÊ', 'EB TIETÊ'), ('EB LARANJAL PAULISTA', 'EB LARANJAL PAULISTA'), ('EB PIRAJU', 'EB PIRAJU'), ('EB IBIÚNA', 'EB IBIÚNA'), ('EB ITAPEVA', 'EB ITAPEVA'), ('EB ITATINGA', 'EB ITATINGA'), ('EB ITU', 'EB ITU'), ('EB PIEDADE', 'EB PIEDADE'), ('EB PORTO FELIZ', 'EB PORTO FELIZ'), ('EB VOTORANTIM', 'EB VOTORANTIM'), ('EB SANTA ROSÁLIA', 'EB SANTA ROSÁLIA'), ('EB ZONA NORTE', 'EB ZONA NORTE'), ('EB ÉDEM', 'EB ÉDEM')], max_length=50),
        ),
    ]
