# Generated by Django 5.1.4 on 2025-02-14 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0002_alter_cidade_latitude_alter_cidade_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='descricao',
            field=models.TextField(blank=True, help_text='Informações relevantes sobre o município', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='posto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='municipios.posto', verbose_name='Contato do Posto'),
        ),
    ]
