# Generated by Django 5.1.4 on 2025-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0003_cidade_descricao_alter_contato_posto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='codigo_ibge',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
