# Generated by Django 5.1.4 on 2025-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0004_cidade_codigo_ibge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
