# Generated by Django 5.1.4 on 2025-02-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0005_cidade_geojson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='geojson',
            new_name='geodata',
        ),
    ]
