# Generated by Django 5.1.4 on 2025-02-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0006_rename_geojson_cidade_geodata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='codigo_ibge',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='geodata',
        ),
    ]
