# Generated by Django 5.1.4 on 2025-02-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0007_remove_cidade_codigo_ibge_remove_cidade_geodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='quartel',
            field=models.ImageField(blank=True, help_text='Formato: PNG/JPG. Tamanho máximo: 2MB', null=True, upload_to='img/quartel/%Y/%m/%d/', verbose_name='Quartel'),
        ),
    ]
