# Generated by Django 5.1.4 on 2025-01-08 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicional', '0001_initial'),
        ('efetivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_lp_ats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ultimo_adicional', models.DateField()),
                ('data_ultimo_lp', models.DateField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_lp_ats', to='efetivo.cadastro')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
