# Generated by Django 5.1.4 on 2025-02-27 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('tipo', models.CharField(default='Lembrete', max_length=50)),
                ('cor', models.CharField(default='#3788d8', max_length=7)),
                ('visibilidade', models.CharField(choices=[('privado', 'Privado'), ('publico', 'Público')], default='privado', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tipo', models.CharField(default='Tarefa', max_length=50)),
                ('cor', models.CharField(default='#3788d8', max_length=7)),
                ('visibilidade', models.CharField(choices=[('privado', 'Privado'), ('publico', 'Público')], default='privado', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
