# Generated by Django 5.1.4 on 2025-02-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_lembrete_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='tipo',
            field=models.CharField(default='Lembrete', max_length=50),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(default='Tarefa', max_length=50),
        ),
    ]
