# Generated by Django 5.1.4 on 2025-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_lembrete_tipo_tarefa_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.AddField(
            model_name='lembrete',
            name='cor',
            field=models.CharField(default='#3788d8', max_length=7),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='cor',
            field=models.CharField(default='#3788d8', max_length=7),
        ),
    ]
