# Generated by Django 5.1.4 on 2025-02-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='arquivo',
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('DOC', 'Documento'), ('SHEET', 'Planilha'), ('IMAGEM', 'Imagem'), ('TEXT', 'Texto'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10),
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('DOC', 'Documento'), ('SHEET', 'Planilha'), ('IMAGEM', 'Imagem'), ('TEXT', 'Texto'), ('OUTRO', 'Outro')], max_length=10)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='documentos.documento')),
            ],
        ),
    ]
