# Generated by Django 5.1.4 on 2025-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documento_data_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='data_documento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_publicacao',
            field=models.DateField(),
        ),
    ]
